import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "./(components)/Nav";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Ticket App",
	description: "Generated by Tech Team",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex flex-col h-screen">
					<Nav />
					<div className="flex-grow overflow-y-auto bg-slate-200 text-gray-800">
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
